//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject.Fonksiyonlar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunler
    {
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> BirimFiyat { get; set; }
        public Nullable<int> StokMiktari { get; set; }
        public string TedarikciFirma { get; set; }
        public string TedarikciTel { get; set; }
        public string TedarikciAdres { get; set; }
    }
}
