//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeAtHome.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpPro102SEntities2 : DbContext
    {
        public ErpPro102SEntities2()
            : base("name=ErpPro102SEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sehirler> Sehirler { get; set; }
        public DbSet<tblDepartmanlar> tblDepartmanlar { get; set; }
        public DbSet<tblDoktorlar> tblDoktorlar { get; set; }
        public DbSet<tblFirmalar> tblFirmalar { get; set; }
        public DbSet<tblHastaneler> tblHastaneler { get; set; }
        public DbSet<tblPersoneller> tblPersoneller { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblFirmaDetaylar> tblFirmaDetaylar { get; set; }
        public DbSet<tblHastaneDetaylar> tblHastaneDetaylar { get; set; }
        public DbSet<tblHastaneTipleri> tblHastaneTipleri { get; set; }
        public DbSet<tblStokDurum> tblStokDurum { get; set; }
        public DbSet<tblUrunGirisAlt> tblUrunGirisAlt { get; set; }
        public DbSet<tblUrunGirisUst> tblUrunGirisUst { get; set; }
        public DbSet<tblUrunKayitAlt> tblUrunKayitAlt { get; set; }
        public DbSet<tblUrunKayitUst> tblUrunKayitUst { get; set; }
    }
}
