//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeAtHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmanlar
    {
        public tblDepartmanlar()
        {
            this.tblDetaylar = new HashSet<tblDetaylar>();
        }
    
        public int Id { get; set; }
        public string DepartmanKodu { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<tblDetaylar> tblDetaylar { get; set; }
    }
}
