//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeAtHome.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmanlar
    {
        public tblDepartmanlar()
        {
            this.tblPersoneller = new HashSet<tblPersoneller>();
            this.tblFirmaDetaylar = new HashSet<tblFirmaDetaylar>();
            this.tblHastaneDetaylar = new HashSet<tblHastaneDetaylar>();
        }
    
        public int Id { get; set; }
        public string DepartmanKodu { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<tblPersoneller> tblPersoneller { get; set; }
        public virtual ICollection<tblFirmaDetaylar> tblFirmaDetaylar { get; set; }
        public virtual ICollection<tblHastaneDetaylar> tblHastaneDetaylar { get; set; }
    }
}
